# Autogenerated wrapper script for lapackpp_jll for x86_64-apple-darwin
export liblapackpp

using CompilerSupportLibraries_jll
using OpenBLAS32_jll
using blaspp_jll
JLLWrappers.@generate_wrapper_header("lapackpp")
JLLWrappers.@declare_library_product(liblapackpp, "@rpath/liblapackpp.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, OpenBLAS32_jll, blaspp_jll)
    JLLWrappers.@init_library_product(
        liblapackpp,
        "lib/liblapackpp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
